### ISSUE TITLE
Lookup by BsonBinary not working

### ISSUE THREAD

**Issue by sanmadjack** [mongo-dart/mongo_dart#109]
I'm querying using this selector:

`where.eq(idField, new BsonBinary.fromHexString(id)
`
And getting this error:

```
Tried calling: length
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      BsonBinary.byteLength (package:bson/src/types/binary.dart:208:32)
#3      elementSize (package:bson/src/bson_type.dart:95:33)
#4      BsonMap.dataSize.<anonymous closure> (package:bson/src/types/map.dart:11:25)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#6      BsonMap.dataSize (package:bson/src/types/map.dart:9:12)
#7      BsonMap.byteLength (package:bson/src/types/map.dart:18:17)
#8      elementSize (package:bson/src/bson_type.dart:95:33)
#9      BsonMap.dataSize.<anonymous closure> (package:bson/src/types/map.dart:11:25)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#11     BsonMap.dataSize (package:bson/src/types/map.dart:9:12)
#12     BsonMap.byteLength (package:bson/src/types/map.dart:18:17)
#13     MongoQueryMessage.messageLength (package:mongo_dart/src/database/mongo_query_message.dart:36:67)
#14     MongoQueryMessage.serialize (package:mongo_dart/src/database/mongo_query_message.dart:44:40)
#15     _Connection._sendBuffer (package:mongo_dart/src/network/connection.dart:86:35)
#16     _Connection.query (package:mongo_dart/src/network/connection.dart:98:7)
#17     Db.executeDbCommand (package:mongo_dart/src/database/db.dart:263:41)
<asynchronous suspension>
#18     DbCollection.count (package:mongo_dart/src/database/dbcollection.dart:93:15)

```
Am I doing it wrong?

**Comment by vadimtsushko** [comment]
If your id field is of type https://docs.mongodb.com/manual/reference/method/ObjectId/ it probably shoud be something like  

```where.eq(idField, new ObjectId.fromHexString(id))```

or 

```where.id(new ObjectId.fromHexString(id))```

if  idField is `_id`

**Comment by sanmadjack** [comment]
It's not, It's a custom field I'm attempting to store a sha256 hash in.

**Comment by vadimtsushko** [comment]
I see. 
Yes, I think it is definitely a bug.
