### ISSUE TITLE
Socket error SocketException: OS Error: Broken pipe, errno = 32

### ISSUE THREAD

**Issue by u007** [mongo-dart/mongo_dart#173]
im connecting to mongodb atlas using connection string:
```
mongodb://username:password@productionxxxx-shard-00-00-ssss.mongodb.net/dbname?authSource=admin
```

getting

```
SEVERE: Socket error SocketException: OS Error: Broken pipe, errno = 32, address = productionxxxx-shard-00-00-ssss.mongodb.net, port = 38552 null
```
the mongodb version is 3.6.15

**Comment by u007** [comment]
and sometimes getting this:
```
Query MongoQueryMessage(2, zipply.$cmd,numberToReturn:1, {ismaster: 1})
_sendBuffer true
Unhandled exception:
MongoDB ConnectionException: connection closed.
#0      _ConnectionManager._connect (package:mongo_dart/src/network/connection_manager.dart:25)
#1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:78)
#2      _RootZone.runBinary (dart:async/zone.dart:1384)
#3      _FutureListener.handleError (dart:async/future_impl.dart:151)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:690)
#5      Future._propagateToListeners (dart:async/future_impl.dart:711)
#6      Future._completeError (dart:async/future_impl.dart:530)
#7      Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:478)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173)

```

**Comment by vivekwadhwani** [comment]
Me too! I have a similar error :
`SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 35464`

**Comment by rravithejareddy** [comment]
Just use 10.0.2.2 instead of localhost or 127.0.0.1, if you are working on emulator.
