### ISSUE TITLE
Unable to authenticate on mongo atlas 6.0.14

### ISSUE THREAD

**Issue by tperraut** [mongo-dart/mongo_dart#371]
Hello, I try to use this lib but I was unable to authenticate on a database instance in version 6.0.14, I tried on another one in 7.0.7 and everything is working great. I tried with multiple user/pass and I have multiple services in different language than can authenticate without issue with those credentials.

Here is the error : 
```
start
{ok: 0.0, errmsg: Authentication failed., code: 18, codeName: AuthenticationFailed, $clusterTime: {clusterTime: Timestamp(1711558053, 1), signature: {hash: BsonBinary(72def75a31ced156aaad2dc72c7449d106bdc143), keyId: 7298757278386094082}}, operationTime: Timestamp(1711558053, 1)}
{ok: 0.0, errmsg: Authentication failed., code: 18, codeName: AuthenticationFailed, $clusterTime: {clusterTime: Timestamp(1711558053, 1), signature: {hash: BsonBinary(72def75a31ced156aaad2dc72c7449d106bdc143), keyId: 7298757278386094082}}, operationTime: Timestamp(1711558053, 1)}
{ok: 0.0, errmsg: Authentication failed., code: 18, codeName: AuthenticationFailed, $clusterTime: {clusterTime: Timestamp(1711558053, 1), signature: {hash: BsonBinary(72def75a31ced156aaad2dc72c7449d106bdc143), keyId: 7298757278386094082}}, operationTime: Timestamp(1711558053, 1)}
#0      SaslAuthenticator.modernAuthenticate (package:mongo_dart/src/auth/sasl_authenticator.dart:89:9)
<asynchronous suspension>
#1      Db.authenticate (package:mongo_dart/src/database/db.dart:766:5)
<asynchronous suspension>
#2      ConnectionManager._connect (package:mongo_dart/src/network/connection_manager.dart:98:9)
<asynchronous suspension>
#3      ConnectionManager.open (package:mongo_dart/src/network/connection_manager.dart:142:9)
<asynchronous suspension>
#4      Db.open (package:mongo_dart/src/database/db.dart:485:7)
<asynchronous suspension>
#5      main (package:pony_chaser_app/test.dart:10:5)
<asynchronous suspension>
```
I took the liberty of adding a `print(result);` [here](https://github.com/mongo-dart/mongo_dart/blob/c65dfe005e0f883fbbc0d0fd451a605be033478f/lib/src/auth/sasl_authenticator.dart#L88), that's the first 3 lines of the sample above.

Also here is the minimum sample I use : 
```dart
import 'package:mongo_dart/mongo_dart.dart' as mongo_dart;

void main() async {
  print("start");
  var db = await mongo_dart.Db.create(
    "mongodb+srv://user:password@myserver.mongodb.net/core",
  );
  try {
    await db.open();
  } catch (e) {
    print((e as mongo_dart.MongoDartError).stackTrace?.toString());
    rethrow;
  }
  print("connected");
  var collection = db.collection('vehicles_electisan');
  var pipeline = mongo_dart.AggregationPipelineBuilder().build();
  print("start watching");
  var stream = collection.watch(pipeline,
      changeStreamOptions:
          mongo_dart.ChangeStreamOptions(fullDocument: 'updateLookup'));

  var close = false;
  var controller = stream.listen((event) {
    print(event.fullDocument.toString());

    close = true;
  });

  await Future.doWhile(() async {
    if (close) {
      print("closing");
      await controller.cancel();
      await db.close();
      return false;
    }
    await Future.delayed(const Duration(seconds: 2));
    return true;
  });
}
```

And I never reached the "connected" log with the 6.0.14 database.

Thanks for your work.

**Comment by giorgiofran** [comment]
Which `AuthenticationScheme ` are you using?

**Comment by tperraut** [comment]
[SCRAM](https://docs.mongodb.com/manual/core/security-scram-sha-1/) never had issue with this before

**Comment by tperraut** [comment]
Is there a way to force a specific AuthenticationScheme when using db.open() ?
