### ISSUE TITLE
Error with dart-1.17.1

### ISSUE THREAD

**Issue by lejard-h** [mongo-dart/mongo_dart#98]
Hi, since the last version of dart `1.17.1` I have this error

```dart
Unhandled exception:
ConnectionPoolException: Failed to open connection. Cause: type '_SinkTransformerStreamSubscription<List<int>, MongoReplyMessage>' is not a subtype of type 'StreamSubscription<List<int>>' of 'value' where
  _SinkTransformerStreamSubscription is from dart:async
  MongoReplyMessage is from package:mongo_dart/mongo_dart.dart
  List is from dart:core
  int is from dart:core
  MongoReplyMessage is from package:mongo_dart/mongo_dart.dart
  StreamSubscription is from dart:async
  List is from dart:core
  int is from dart:core

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:938)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

I am using Redstone with redstone_mapper_mongo, maybe it's coming from here but I don't know

**Comment by lejard-h** [comment]
Okay sorry about that, `redstone_mapper_mongo` is using an old version of `mongo_dart`, override dependencies resolve the problem
